### ISSUE TITLE
App name

### ISSUE THREAD

**Issue by darlingtim** [BuildForSDG/Team-059-backend#9]
**application has no befitting name**
An application should have a brand name which should distinguish it from other apps.

**Solution Description**
A name that suggests that it is an educational app meant to increase the number of qualified teachers.

**Describe alternatives considered**
Edu social , Edu Connect, Teaching profession, Tutor mastery, teach The Teacher,  Education Raise, Education Boost.

**Comment by Jerry299** [comment]
I have an Idea, "Torch Bearers" should be a great name, what do you guys think?

**Comment by peterchijioke** [comment]
I'm suggesting *EduVantage or EduGrowth

**Comment by chifum** [comment]
I suggest we name it Lecture Hall(LH) or iLearn, iLearners.

**Comment by Niyiojeyinka** [comment]
Want to suggest Qteach ,from 'qualified teacher,
And also 'teachify' 


Or 'Quech'. From same phrase

**Comment by darlingtim** [comment]
Team members have temporary decided to choose `EduGrowth` as our App name
